export const HANDLE_IS_OPEN = 'HANDLE_IS_OPEN';
export const GET_DOCTORS_DATA = 'GET_DOCTORS_DATA';
export const HANDLE_DATA_CHANGE = 'HANDLE_DATA_CHANGE';
export const SET_BOOKED_HRS = 'SET_BOOKED_HRS';
